version: 2
updates:
#  - package-ecosystem: npm
#    directory: "/"
#    schedule:
#      interval: weekly
#      time: "10:00"
#      timezone: Asia/Tokyo
#    open-pull-requests-limit: 1
#    target-branch: main
#    reviewers:
#      - mryhryki
#    assignees:
#      - mryhryki
#    labels:
#      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
      timezone: Asia/Tokyo
    target-branch: main
    reviewers:
      - mryhryki
    assignees:
      - mryhryki
    labels:
      - dependencies

