name: add_reading_log
env:
  TZ: "Asia/Tokyo"
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: URL
      title:
        required: true
        description: Title

jobs:
  add_reading_log:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add reading log
        run: bash ./script/reading_log/add_reading_log.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_URL: ${{ github.event.inputs.url }}
          LOG_TITLE: ${{ github.event.inputs.title }}
