name: add_scrap
env:
  TZ: "Asia/Tokyo"

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
        description: Title
      text:
        required: true
        description: Text

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  add_scrap:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add scrap
        run: bash ./.github/script/shell/add_scrap.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCRAP_TITLE: ${{ github.event.inputs.title }}
          SCRAP_TEXT: ${{ github.event.inputs.text }}
