name: deploy_aws
env:
  TZ: "Asia/Tokyo"
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Update npm
        run: npm install -g npm
      - name: Show environment
        run: |
          pwd
          ls -la
          node -v
          npm -v
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::644989259572:role/ci-portfolio-role
          aws-region: ap-northeast-1
      - name: Prepare
        run: npm ci
      - name: Build site
        run: npm run site:build
      - name: Update site
        run: npm run site:update
