name: generate_holidays
env:
  TZ: "Asia/Tokyo"

on:
  schedule:
    - cron: "0 0 1 3 *" # UTC
  workflow_dispatch:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate holidays
        run: |
          npm i -g npm
          npm run generate:holidays
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Generate holidays.json"
          commit-message: "Generate holidays.json"
          branch: "generate-holidays"
          delete-branch: true
          branch-suffix: timestamp
          reviewers: mryhryki
