name: update_packages
env:
  TZ: "Asia/Tokyo"

on:
  schedule:
    - cron: "0 20 * * SUN" # UTC
  workflow_dispatch:

jobs:
  update_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Update npm
        run: npm install -g npm
      - name: Update packages
        run: |
          cd ./.github/script/
          npm exec -- npm-check-updates -u
          npm install
          npm audit fix || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Update package.json"
          commit-message: "Update package.json"
          branch: "update-packages"
          delete-branch: true
          branch-suffix: timestamp
          reviewers: mryhryki
