name: update_packages
env:
  TZ: "Asia/Tokyo"
  ACTIONS_RUNNER_DEBUG: "true"
  ACTIONS_STEP_DEBUG: "true"

on:
  schedule:
    - cron: "0 20 * * SUN" # UTC

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Update packages
        run: |
          npm i -g npm
          npm exec -- npm-check-updates -u
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update package.json"
          commit-message: "Update package.json"
          branch: "update-packages"
          delete-branch: true
          branch-suffix: timestamp
          reviewers: mryhryki
